---
mode: upstart

email:
  server: smtp.gmail.com:587
  username: blah@vektra.io
  password: foobar

services:
  - name: unicorn
    memory: 1000Mb

  - name: sidekiq
    memory: 500Mb
    on:
      - event: memory/limit
        webhook: https://stats.vektra.io/import

on:
  - event: memory/limit
    process: restart
